### ISSUE TITLE
OSError: Unable to load weights from pytorch checkpoint file for '/content/BERT_MRC_NER_chinese/pretrained_model/hfl_chinese-roberta-wwm-ext/pytorch_model.bin'

### ISSUE THREAD

**Issue by dsuanya** [taishan1994/BERT_MRC_NER_chinese#6]
你好，我下载pytorch_model.bin好像有点问题？请问该怎么解决？我是在colab跑的，删除transformers也无法解决这个问题。真的非常非常感谢您的回答！！！

**Comment by taishan1994** [comment]
> 你好，我下载pytorch_model.bin好像有点问题？请问该怎么解决？我是在colab跑的，删除transformers也无法解决这个问题。真的非常非常感谢您的回答！！！

去这个地址，找到相关文件的链接，然后!wget 链接。

**Comment by dsuanya** [comment]
非常感谢！！我已经解决啦

**Comment by dsuanya** [comment]
> > 你好，我下载pytorch_model.bin好像有点问题？请问该怎么解决？我是在colab跑的，删除transformers也无法解决这个问题。真的非常非常感谢您的回答！！！
> 
> 去这个地址，找到相关文件的链接，然后!wget 链接。

非常感谢！！我已经解决啦
